name: Publish to npm

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Check version is new
        id: version_check
        run: |
          LOCAL=$(node -p "require('./package.json').version")
          PUBLISHED=$(npm view create-01x-project version 2>/dev/null || echo "0.0.0")
          echo "local=$LOCAL" >> $GITHUB_OUTPUT
          echo "published=$PUBLISHED" >> $GITHUB_OUTPUT
          if [ "$LOCAL" = "$PUBLISHED" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "Version $LOCAL already published — skipping."
          else
            echo "skip=false" >> $GITHUB_OUTPUT
            echo "Publishing $LOCAL (was $PUBLISHED)"
          fi

      - name: Publish
        if: steps.version_check.outputs.skip == 'false'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
